
package fr.treeptik.ejbsample.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonneWSService", targetNamespace = "http://webservice.ejbsample.treeptik.fr/", wsdlLocation = "file:/home/ic06/.wildfly/wildfly-10.0.0.Final/standalone/data/wsdl/EJBSample.war/PersonneWSService.wsdl")
public class PersonneWSService
    extends Service
{

    private final static URL PERSONNEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONNEWSSERVICE_EXCEPTION;
    private final static QName PERSONNEWSSERVICE_QNAME = new QName("http://webservice.ejbsample.treeptik.fr/", "PersonneWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/ic06/.wildfly/wildfly-10.0.0.Final/standalone/data/wsdl/EJBSample.war/PersonneWSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONNEWSSERVICE_WSDL_LOCATION = url;
        PERSONNEWSSERVICE_EXCEPTION = e;
    }

    public PersonneWSService() {
        super(__getWsdlLocation(), PERSONNEWSSERVICE_QNAME);
    }

    public PersonneWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONNEWSSERVICE_QNAME, features);
    }

    public PersonneWSService(URL wsdlLocation) {
        super(wsdlLocation, PERSONNEWSSERVICE_QNAME);
    }

    public PersonneWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONNEWSSERVICE_QNAME, features);
    }

    public PersonneWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonneWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonneWS
     */
    @WebEndpoint(name = "PersonneWSPort")
    public PersonneWS getPersonneWSPort() {
        return super.getPort(new QName("http://webservice.ejbsample.treeptik.fr/", "PersonneWSPort"), PersonneWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonneWS
     */
    @WebEndpoint(name = "PersonneWSPort")
    public PersonneWS getPersonneWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ejbsample.treeptik.fr/", "PersonneWSPort"), PersonneWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONNEWSSERVICE_EXCEPTION!= null) {
            throw PERSONNEWSSERVICE_EXCEPTION;
        }
        return PERSONNEWSSERVICE_WSDL_LOCATION;
    }

}
